Fix some warning flags.

diff --git a/script/ghci-flags b/script/ghci-flags
--- a/script/ghci-flags
+++ b/script/ghci-flags
@@ -61,13 +61,12 @@ function flags {
   echo "-Wno-missed-specialisations"
   echo "-Wno-missing-import-lists"
   echo "-Wno-missing-local-signatures"
-  echo "-Wno-missing-safe-haskell-mode"
   echo "-Wno-monomorphism-restriction"
   echo "-Wno-name-shadowing"
   echo "-Wno-safe"
   echo "-Wno-unsafe"
-  [[ "$ghc_version" = 8.8.* ]] || [[ "$ghc_version" = 8.10.* ]] && echo "-Wno-missing-deriving-strategies" || true
-  [[ "$ghc_version" = 8.10.* ]] && echo "-Wno-missing-safe-haskell-mode" && echo "-Wno-prepositive-qualified-module" && echo "-Wno-unused-packages"
+  [[ "$ghc_version" = 8.8.* ]] || [[ "$ghc_version" = 8.10.* ]] || [[ "$ghc_version" = 9.0.* ]] && echo "-Wno-missing-deriving-strategies" || true
+  [[ "$ghc_version" = 8.10.* ]] || [[ "$ghc_version" = 9.0.* ]] && echo "-Wno-missing-safe-haskell-mode" && echo "-Wno-prepositive-qualified-module" && echo "-Wno-unused-packages"
 
   echo "-XDeriveTraversable"
   echo "-XDerivingStrategies"
